"""create sentiments table

Revision ID: 2b2d05612323
Revises: 
Create Date: 2024-07-27 01:37:04.980277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2d05612323'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('neutral', sa.Float(), nullable=True),
    sa.Column('positive', sa.Float(), nullable=True),
    sa.Column('negative', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiments_id'), 'sentiments', ['id'], unique=False)
    op.create_index(op.f('ix_sentiments_text'), 'sentiments', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiments_text'), table_name='sentiments')
    op.drop_index(op.f('ix_sentiments_id'), table_name='sentiments')
    op.drop_table('sentiments')
    # ### end Alembic commands ###
